version: "3.5"

services:

  sns:
    container_name: sns
    build:
      context: ./services/sns
      dockerfile: Dockerfile-prod
    ports:
      - "5001:5000"
    environment:
      APP_SETTINGS: project.config.ProductionConfig
      DATABASE_URL: postgres://postgres:postgres@sns-db:5432/sns_prod
      DATABASE_TEST_URL: postgres://postgres:postgres@sns-db:5432/sns_test
      SECRET_KEY: my_precious
    depends_on:
      - sns-db
    links:
      - sns-db

  sns-db:
    container_name: sns-db
    build:
      context: ./services/sns/project/db
      dockerfile: Dockerfile
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
