version: "3.5"

services:

  sns:
    container_name: sns
    build:
      context: ./services/sns
      dockerfile: Dockerfile-dev
    volumes:
      - "./services/sns:/usr/src/app"
    ports:
      - "5001:5000"
    environment:
      APP_SETTINGS: project.config.DevelopmentConfig
      DATABASE_URL: postgres://postgres:postgres@sns-db:5432/sns_dev
      DATABASE_TEST_URL: postgres://postgres:postgres@sns-db:5432/sns_test
    depends_on:
      - sns-db
    links:
      - sns-db

  sns-db:
    container_name: sns-db
    build:
      context: ./services/sns/project/db
      dockerfile: Dockerfile
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
