FROM python:3.6.4

# install OS environment dependencies
RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends netcat \
  && apt-get -q clean

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# install Python app requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# add entrypoint.sh
COPY ./entrypoint-prod.sh /usr/src/app/entrypoint-prod.sh

# add app
COPY . /usr/src/app

# run server
CMD ["./entrypoint-prod.sh"]
